/**
 * Entry point: loads assets, manages the menu screens (landing, time portals,
 * how-to, settings), and launches the Game. Owns meta-progression (unlocked
 * eras), user settings, and the shared Audio instance.
 */
import { MODE } from './core/constants.js';
import { ERAS } from './core/eras.js';
import { isBranchEra } from './core/eraGraph.js';
import { Progress } from './persistence/Progress.js';
import { Settings } from './persistence/Settings.js';
import { SaveManager } from './persistence/SaveManager.js';
import { parseRealityFromUrl } from './core/RealityCode.js';
import { dailyChallenge } from './core/DailyChallenge.js';
import { getEra } from './core/eras.js';
import { getEraUI, variantInfo } from './core/eraTheme.js';
import { Audio } from './systems/Audio.js';
import { LandingScene } from './ui/LandingScene.js';
import { Game } from './Game.js';

const screens = {};
let game = null;
let landingScene = null;
let chosenMode = MODE.SURVIVAL;
let introStep = 0;
let journeyLaunch = null;

const JOURNEY_INTRO = [
  {
    number: 'I', icon: '🌍', kicker: 'More than four billion years ago',
    title: 'There were no heroes.',
    body: 'No creatures. No cities. No history. Only a young Earth, violent oceans, and chemistry waiting for one impossible accident.',
  },
  {
    number: 'II', icon: '✦', kicker: 'That accident is yours',
    title: 'Begin smaller than life.',
    body: 'Move through the primordial ocean. Bring matter and energy together. If the conditions are right, the first living cell will exist because of you.',
  },
  {
    number: 'III', icon: '🌀', kicker: 'Then the world remembers',
    title: 'Guide what comes after.',
    body: 'Life will evolve. Civilizations will rise. Your choices will split history into realities you cannot yet see.',
  },
];

const progress = new Progress();
const settings = new Settings();
const audio = new Audio({ sound: settings.get('sound'), music: settings.get('music') });

const sprites = {};

function loadSprites() {
  const manifest = {
    cow: 'assets/generated/sprites/cow.png',
    pig: 'assets/generated/sprites/pig.png',
    chicken: 'assets/generated/sprites/chicken.png',
    goat: 'assets/generated/sprites/goat.png',
    noah: 'assets/generated/sprites/player_idle.png',
    player: 'assets/generated/sprites/player.png',
    cell: 'assets/generated/sprites/cell.png',
    blockAtlas: 'assets/generated/textures/blocks.png',
    blockAtlasExtra: 'assets/generated/textures/blocks_extra.png',
    effects: 'assets/generated/effects/effects.png',
    // Dinosaurs + enemy sprites (generated by tools/gen-sprites.mjs).
    stego: 'assets/generated/sprites/stego.png',
    trike: 'assets/generated/sprites/trike.png',
    raptor: 'assets/generated/sprites/raptor.png',
    rex: 'assets/generated/sprites/rex.png',
    wolf: 'assets/generated/sprites/wolf.png',
    boar: 'assets/generated/sprites/boar.png',
    raider: 'assets/generated/sprites/raider.png',
    bandit: 'assets/generated/sprites/bandit.png',
    machine: 'assets/generated/sprites/machine.png',
  };
  for (const n in manifest) {
    const img = new Image();
    img.src = manifest[n];
    sprites[n] = img;
  }
}

function show(id) {
  for (const key in screens) screens[key].classList.toggle('active', key === id);
  // Only animate the landing backdrop while the landing screen is visible.
  if (landingScene) {
    if (id === 'landing') landingScene.start();
    else landingScene.stop();
  }
}

function startGame({ eraId, mode, save, reality, daily, thread }) {
  if (game) game.stop();
  audio.resume(); // unlock audio from the click that launched the game
  game = new Game({
    canvas: document.getElementById('gameCanvas'),
    hudRoot: document.getElementById('hud'),
    sprites,
    progress,
    settings,
    audio,
    onExit: () => { game = null; refreshLanding(); show('landing'); },
    onDailyComplete: (key) => progress.completeDaily(key),
  });
  if (save) game.loadSave(save);
  else if (reality) {
    // Land the player in a fixed world (a friend's link, or the daily).
    game.newWorld(reality.era, reality.mode, { seed: reality.seed, variant: reality.variant });
  } else game.newWorld(eraId, mode);
  if (thread) game.thread = thread;
  if (daily) game.daily = daily; // attach the goal so completion is tracked
  show('game');
  game.start();
}

function refreshLanding() {
  const cont = document.getElementById('continueBtn');
  const has = SaveManager.hasSave();
  cont.classList.toggle('disabled', !has);
  cont.disabled = !has;
  const eras = document.getElementById('erasBtn');
  if (eras) eras.classList.toggle('hidden', progress.unlockedList().length <= 1);
  renderDailyCard();
}

function showJourneyIntro(launch = null) {
  journeyLaunch = launch || (() => {
    settings.set('seenPrelife', false);
    settings.set('seenTutorial', '');
    startGame({ eraId: 'cell', mode: MODE.SURVIVAL });
  });
  introStep = 0;
  renderJourneyIntro();
  show('intro');
}

function renderJourneyIntro() {
  const step = JOURNEY_INTRO[introStep];
  document.getElementById('introNumber').textContent = step.number;
  document.getElementById('introIcon').textContent = step.icon;
  document.getElementById('introKicker').textContent = step.kicker;
  document.getElementById('introTitle').textContent = step.title;
  document.getElementById('introBody').textContent = step.body;
  document.getElementById('introDots').innerHTML = JOURNEY_INTRO
    .map((_, i) => `<span class="${i === introStep ? 'on' : ''}"></span>`).join('');
  document.getElementById('introNext').textContent =
    introStep === JOURNEY_INTRO.length - 1 ? 'Enter the primordial ocean →' : 'Continue →';
}

let globeRunning = false;
let selectedThread = 'salvador';
let onThreadSelected = null;

function advanceJourneyIntro() {
  if (introStep < JOURNEY_INTRO.length - 1) {
    introStep++;
    renderJourneyIntro();
    return;
  }
  // "New Journey" always replays the complete origin, while Continue preserves
  // the existing local world.
  const launch = journeyLaunch;
  journeyLaunch = null;
  if (launch) {
    launch();
  } else {
    showThreadSelection((selected) => {
      settings.set('seenPrelife', false);
      settings.set('seenTutorial', '');
      startGame({ eraId: 'cell', mode: MODE.SURVIVAL, thread: selected });
    });
  }
}

function showThreadSelection(onSelect) {
  onThreadSelected = onSelect;
  selectedThread = 'salvador';
  const salvadorCard = document.getElementById('threadSalvador');
  const stockholmCard = document.getElementById('threadStockholm');
  salvadorCard?.classList.add('active');
  stockholmCard?.classList.remove('active');
  show('threadSelect');
  startGlobeAnimation(document.getElementById('globeCanvas'), () => selectedThread);
}

function startGlobeAnimation(canvas, getSelectedThread) {
  if (globeRunning || !canvas) return;
  globeRunning = true;
  const ctx = canvas.getContext('2d');
  const w = canvas.width;
  const h = canvas.height;
  const cx = w / 2;
  const cy = h / 2;
  const R = 80;
  let theta = 0;
  
  const blobs = [
    { lat: 20, lon: 0, r: 28 },
    { lat: -25, lon: 60, r: 24 },
    { lat: 45, lon: -90, r: 18 },
    { lat: -35, lon: -35, r: 26 },
    { lat: 30, lon: 130, r: 20 },
    { lat: -15, lon: -110, r: 22 },
    { lat: 60, lon: 15, r: 16 },
  ];

  const dots = {
    salvador: { lat: -12.97, lon: -38.51, color: '#ffab40' },
    stockholm: { lat: 59.33, lon: 18.07, color: '#40c4ff' }
  };

  const frame = () => {
    if (!globeRunning || !screens.threadSelect.classList.contains('active')) {
      globeRunning = false;
      return;
    }
    
    theta += settings.get('reduceMotion') ? 0.002 : 0.008;
    ctx.clearRect(0, 0, w, h);
    
    // 1) Draw ocean sphere base
    const oceanGrad = ctx.createRadialGradient(cx - R * 0.2, cy - R * 0.2, 0, cx, cy, R);
    oceanGrad.addColorStop(0, '#1c2d5e');
    oceanGrad.addColorStop(1, '#0c1229');
    ctx.fillStyle = oceanGrad;
    ctx.beginPath();
    ctx.arc(cx, cy, R, 0, Math.PI * 2);
    ctx.fill();
    
    // 2) Draw continents inside clipping mask
    ctx.save();
    ctx.beginPath();
    ctx.arc(cx, cy, R, 0, Math.PI * 2);
    ctx.clip();
    
    ctx.fillStyle = '#4e7355';
    for (const b of blobs) {
      const lonRot = b.lon - (theta * 180 / Math.PI);
      const lonRad = (lonRot % 360) * Math.PI / 180;
      const latRad = b.lat * Math.PI / 180;
      const cosLon = Math.cos(lonRad);
      
      if (cosLon > 0) {
        const bx = cx + R * Math.sin(lonRad) * Math.cos(latRad);
        const by = cy - R * Math.sin(latRad);
        ctx.beginPath();
        ctx.arc(bx, by, b.r * (0.4 + 0.6 * cosLon), 0, Math.PI * 2);
        ctx.fill();
      }
    }
    
    // 3) Draw Salvador / Stockholm location dots
    const selected = getSelectedThread();
    for (const [key, d] of Object.entries(dots)) {
      const lonRot = d.lon - (theta * 180 / Math.PI);
      const lonRad = (lonRot % 360) * Math.PI / 180;
      const latRad = d.lat * Math.PI / 180;
      const cosLon = Math.cos(lonRad);
      
      if (cosLon > 0) {
        const dx = cx + R * Math.sin(lonRad) * Math.cos(latRad);
        const dy = cy - R * Math.sin(latRad);
        
        const isSel = key === selected;
        const pulse = 1 + 0.25 * Math.sin(Date.now() * 0.008);
        
        ctx.shadowColor = d.color;
        ctx.shadowBlur = isSel ? 12 : 6;
        
        ctx.fillStyle = d.color;
        ctx.beginPath();
        ctx.arc(dx, dy, isSel ? 6 * pulse : 4, 0, Math.PI * 2);
        ctx.fill();
        
        ctx.shadowBlur = 0;
        
        if (isSel) {
          ctx.strokeStyle = d.color;
          ctx.lineWidth = 1.5;
          ctx.beginPath();
          ctx.arc(dx, dy, 10 * pulse, 0, Math.PI * 2);
          ctx.stroke();
        }
      }
    }
    
    ctx.restore();
    
    // 4) Specular radial overlay
    const shine = ctx.createRadialGradient(cx - R * 0.35, cy - R * 0.35, 0, cx, cy, R);
    shine.addColorStop(0, 'rgba(255, 255, 255, 0.16)');
    shine.addColorStop(0.5, 'rgba(255, 255, 255, 0.03)');
    shine.addColorStop(0.85, 'rgba(0, 0, 0, 0.35)');
    shine.addColorStop(1, 'rgba(0, 0, 0, 0.7)');
    
    ctx.fillStyle = shine;
    ctx.beginPath();
    ctx.arc(cx, cy, R, 0, Math.PI * 2);
    ctx.fill();
    
    requestAnimationFrame(frame);
  };
  requestAnimationFrame(frame);
}

function renderDailyCard() {
  const host = document.getElementById('dailyCard');
  if (!host) return;
  // Dailies are a return loop, not opening-minute homework. Reveal them after
  // the player has made a world or reached another age.
  host.classList.toggle('hidden', !SaveManager.hasSave() && progress.unlockedList().length === 1);
  if (host.classList.contains('hidden')) return;
  const ch = dailyChallenge();
  const era = getEra(ch.era);
  const v = variantInfo(ch.era, ch.variant);
  const done = progress.hasDailyDone(ch.dateKey);
  const streak = progress.streak || 0;
  host.innerHTML = `
    <div class="daily-head">🗓️ Daily Challenge ${done ? '<span class="daily-done">✓ done</span>' : ''}${streak > 1 ? `<span class="daily-streak">🔥 ${streak}</span>` : ''}</div>
    <div class="daily-body">
      <span class="daily-era">${era.icon}</span>
      <div><b>${v ? v.name : era.name}</b><small>${ch.goal.icon} ${ch.goal.text}</small></div>
      <button id="dailyPlay" class="btn ${done ? '' : 'primary'} daily-play">${done ? 'Replay' : '▶ Play'}</button>
    </div>`;
  const btn = document.getElementById('dailyPlay');
  if (btn) btn.onclick = () => {
    audio.resume(); audio.play('ui');
    startGame({ reality: { seed: ch.seed, era: ch.era, variant: ch.variant, mode: ch.mode }, daily: ch });
  };
}

function buildPortals() {
  const grid = document.getElementById('eraGrid');
  grid.innerHTML = '';
  for (const era of ERAS) {
    // Branch ages are a surprise reached by *routing* through play, not by
    // picking. Hide them from the portal until the player has discovered one.
    if (isBranchEra(era.id) && !progress.isUnlocked(era.id)) continue;
    const unlocked = progress.isUnlocked(era.id);
    const playable = unlocked && (era.fullyPlayable || chosenMode === MODE.CREATIVE);
    const m = era.manifest || {};
    const [skyA, skyB] = era.sky?.day || ['#456', '#234'];
    const card = document.createElement('div');
    card.className = 'era-card' + (unlocked ? '' : ' locked') + (playable ? '' : ' soon');
    card.dataset.era = era.id;
    const ui = getEraUI(era.id);
    card.style.setProperty('--card-accent', ui.accent);
    card.style.setProperty('--card-edge', ui.edge);
    card.style.setProperty('--card-radius', ui.radius);
    card.style.setProperty('--card-font', ui.font);
    card.style.setProperty('--card-texture', ui.texture);
    // Paint each card with its own era's sky + ground so ages feel distinct.
    card.style.background =
      `linear-gradient(160deg, ${skyA}33, ${skyB}22), var(--panel)`;
    card.style.borderColor = `${era.ground}88`;
    const animals = (m.animals || []).slice(0, 3).join(' · ');
    card.innerHTML = `
      <div class="era-icon" style="filter: drop-shadow(0 2px 6px ${era.ground}aa)">${era.icon}</div>
      <h3>${m.title || era.name}</h3>
      <p class="era-sub">${m.subtitle || era.blurb}</p>
      ${animals ? `<p class="era-meta">🐾 ${animals}</p>` : ''}
      <div class="era-foot">${
        !unlocked ? '🔒 Locked'
          : playable ? '▶ Enter'
            : '🚧 Survival soon · Creative ok'
      }</div>
    `;
    if (playable) {
      card.onclick = () => { audio.play('ui'); startGame({ eraId: era.id, mode: chosenMode }); };
    }
    grid.appendChild(card);
  }
}

function syncSettingsUI() {
  const set = (id, val, checkbox = true) => {
    const e = document.getElementById(id);
    if (!e) return;
    if (checkbox) e.checked = !!val; else e.value = val;
  };
  set('lsSound', settings.get('sound'));
  set('lsMusic', settings.get('music'));
  set('lsReduceMotion', settings.get('reduceMotion'));
  set('lsHaptics', settings.get('haptics'));
  set('lsZoom', settings.get('zoomPref') ?? 1, false);
}

function setMode(mode) {
  chosenMode = mode;
  document.getElementById('modeSurvival').classList.toggle('on', mode === MODE.SURVIVAL);
  document.getElementById('modeCreative').classList.toggle('on', mode === MODE.CREATIVE);
  document.getElementById('modeHint').textContent = mode === MODE.SURVIVAL
    ? '⚔️ Survival: gather, craft, survive, and earn Civ Points to open the next era.'
    : '🎨 Creative: free building with unlimited blocks, in any era you have unlocked.';
  const grid = document.getElementById('eraGrid');
  if (grid && grid.children.length) buildPortals();
}

function wire() {
  screens.landing = document.getElementById('landing');
  screens.intro = document.getElementById('intro');
  screens.threadSelect = document.getElementById('threadSelect');
  screens.portal = document.getElementById('portal');
  screens.howto = document.getElementById('howto');
  screens.settings = document.getElementById('settings');
  screens.game = document.getElementById('game');

  const click = (id, fn) => { const e = document.getElementById(id); if (e) e.onclick = () => { audio.resume(); audio.play('ui'); fn(); }; };

  const salvadorCard = document.getElementById('threadSalvador');
  const stockholmCard = document.getElementById('threadStockholm');
  const selectThread = (id) => {
    selectedThread = id;
    salvadorCard?.classList.toggle('active', id === 'salvador');
    stockholmCard?.classList.toggle('active', id === 'stockholm');
  };
  if (salvadorCard) salvadorCard.onclick = () => { audio.play('ui'); selectThread('salvador'); };
  if (stockholmCard) stockholmCard.onclick = () => { audio.play('ui'); selectThread('stockholm'); };

  click('threadStartBtn', () => {
    const fn = onThreadSelected;
    onThreadSelected = null;
    fn?.(selectedThread);
  });
  click('threadBackBtn', () => {
    globeRunning = false;
    show('intro');
  });

  // A shared reality link (?r=CODE) turns Play into a one-tap jump into that
  // exact world — the friend-sharing loop.
  const shared = parseRealityFromUrl();
  const playBtn = document.getElementById('playBtn');
  if (shared && playBtn) {
    const era = getEra(shared.era);
    const v = variantInfo(shared.era, shared.variant);
    playBtn.textContent = `▶ Play shared reality`;
    const sub = document.querySelector('.subtitle');
    if (sub) sub.textContent = `A friend shared a reality: ${era.icon} ${v ? v.name : era.name}. Press Play to enter their exact world.`;
    click('playBtn', () => showJourneyIntro(() => startGame({ reality: shared })));
  } else {
    click('playBtn', () => showJourneyIntro());
  }
  click('introNext', advanceJourneyIntro);
  click('introBack', () => show('landing'));
  click('prologueBtn', () => showJourneyIntro());
  click('erasBtn', () => { buildPortals(); show('portal'); });
  click('continueBtn', () => {
    const save = SaveManager.load();
    if (save) startGame({ save });
  });
  click('howtoBtn', () => show('howto'));
  click('howtoBack', () => show('landing'));
  click('portalBack', () => show('landing'));
  click('settingsBtn', () => { syncSettingsUI(); show('settings'); });
  click('settingsBack', () => show('landing'));

  // Landing settings — apply immediately and persist, so players can mute
  // before any audio starts.
  const bind = (id, key, apply) => {
    const e = document.getElementById(id);
    if (!e) return;
    e.onchange = e.oninput = () => {
      const v = e.type === 'checkbox' ? e.checked : parseFloat(e.value);
      settings.set(key, v);
      apply?.(v);
    };
  };
  bind('lsSound', 'sound', (v) => audio.setSound(v));
  bind('lsMusic', 'music', (v) => audio.setMusic(v));
  bind('lsReduceMotion', 'reduceMotion', (v) => {
    try { document.body.classList.toggle('reduce-motion', v); } catch (e) { /* ignore */ }
  });
  bind('lsHaptics', 'haptics', (v) => { try { if (v && navigator.vibrate) navigator.vibrate(10); } catch (e) { /* ignore */ } });
  bind('lsZoom', 'zoomPref');

  document.getElementById('modeSurvival').onclick = () => { audio.play('ui'); setMode(MODE.SURVIVAL); };
  document.getElementById('modeCreative').onclick = () => { audio.play('ui'); setMode(MODE.CREATIVE); };

  setMode(MODE.SURVIVAL);
  refreshLanding();
}

window.addEventListener('DOMContentLoaded', () => {
  loadSprites();
  wire();
  // Honor saved reduce-motion before any screen animates.
  if (settings.get('reduceMotion')) document.body.classList.add('reduce-motion');
  const sceneCanvas = document.getElementById('landingScene');
  if (sceneCanvas) landingScene = new LandingScene(sceneCanvas, { reduceMotion: settings.get('reduceMotion') });
  show('landing');
});
