/**
 * Entry point: loads assets, manages the menu screens (landing, time portals,
 * how-to, settings), and launches the Game. Owns meta-progression (unlocked
 * eras), user settings, and the shared Audio instance.
 */
import { MODE } from './core/constants.js';
import { ERAS } from './core/eras.js';
import { Progress } from './persistence/Progress.js';
import { Settings } from './persistence/Settings.js';
import { SaveManager } from './persistence/SaveManager.js';
import { parseRealityFromUrl } from './core/RealityCode.js';
import { dailyChallenge } from './core/DailyChallenge.js';
import { getEra } from './core/eras.js';
import { variantInfo } from './core/eraTheme.js';
import { Audio } from './systems/Audio.js';
import { LandingScene } from './ui/LandingScene.js';
import { Game } from './Game.js';

const screens = {};
let game = null;
let landingScene = null;
let chosenMode = MODE.SURVIVAL;

const progress = new Progress();
const settings = new Settings();
const audio = new Audio({ sound: settings.get('sound'), music: settings.get('music') });

const sprites = {};

function loadSprites() {
  const manifest = {
    cow: 'assets/generated/sprites/cow.png',
    pig: 'assets/generated/sprites/pig.png',
    chicken: 'assets/generated/sprites/chicken.png',
    goat: 'assets/generated/sprites/goat.png',
    noah: 'assets/generated/sprites/player_idle.png',
    player: 'assets/generated/sprites/player.png',
    cell: 'assets/generated/sprites/cell.png',
    blockAtlas: 'assets/generated/textures/blocks.png',
    blockAtlasExtra: 'assets/generated/textures/blocks_extra.png',
    effects: 'assets/generated/effects/effects.png',
    // Dinosaurs + enemy sprites (generated by tools/gen-sprites.mjs).
    stego: 'assets/generated/sprites/stego.png',
    trike: 'assets/generated/sprites/trike.png',
    raptor: 'assets/generated/sprites/raptor.png',
    rex: 'assets/generated/sprites/rex.png',
    wolf: 'assets/generated/sprites/wolf.png',
    boar: 'assets/generated/sprites/boar.png',
    raider: 'assets/generated/sprites/raider.png',
    bandit: 'assets/generated/sprites/bandit.png',
    machine: 'assets/generated/sprites/machine.png',
  };
  for (const n in manifest) {
    const img = new Image();
    img.src = manifest[n];
    sprites[n] = img;
  }
}

function show(id) {
  for (const key in screens) screens[key].classList.toggle('active', key === id);
  // Only animate the landing backdrop while the landing screen is visible.
  if (landingScene) {
    if (id === 'landing') landingScene.start();
    else landingScene.stop();
  }
}

function startGame({ eraId, mode, save, reality, daily }) {
  if (game) game.stop();
  audio.resume(); // unlock audio from the click that launched the game
  game = new Game({
    canvas: document.getElementById('gameCanvas'),
    hudRoot: document.getElementById('hud'),
    sprites,
    progress,
    settings,
    audio,
    onExit: () => { game = null; refreshLanding(); show('landing'); },
    onDailyComplete: (key) => progress.completeDaily(key),
  });
  if (save) game.loadSave(save);
  else if (reality) {
    // Land the player in a fixed world (a friend's link, or the daily).
    game.newWorld(reality.era, reality.mode, { seed: reality.seed, variant: reality.variant });
  } else game.newWorld(eraId, mode);
  if (daily) game.daily = daily; // attach the goal so completion is tracked
  show('game');
  game.start();
}

function refreshLanding() {
  const cont = document.getElementById('continueBtn');
  const has = SaveManager.hasSave();
  cont.classList.toggle('disabled', !has);
  cont.disabled = !has;
  renderDailyCard();
}

function renderDailyCard() {
  const host = document.getElementById('dailyCard');
  if (!host) return;
  const ch = dailyChallenge();
  const era = getEra(ch.era);
  const v = variantInfo(ch.era, ch.variant);
  const done = progress.hasDailyDone(ch.dateKey);
  const streak = progress.streak || 0;
  host.innerHTML = `
    <div class="daily-head">🗓️ Daily Challenge ${done ? '<span class="daily-done">✓ done</span>' : ''}${streak > 1 ? `<span class="daily-streak">🔥 ${streak}</span>` : ''}</div>
    <div class="daily-body">
      <span class="daily-era">${era.icon}</span>
      <div><b>${v ? v.name : era.name}</b><small>${ch.goal.icon} ${ch.goal.text}</small></div>
      <button id="dailyPlay" class="btn ${done ? '' : 'primary'} daily-play">${done ? 'Replay' : '▶ Play'}</button>
    </div>`;
  const btn = document.getElementById('dailyPlay');
  if (btn) btn.onclick = () => {
    audio.resume(); audio.play('ui');
    startGame({ reality: { seed: ch.seed, era: ch.era, variant: ch.variant, mode: ch.mode }, daily: ch });
  };
}

function buildPortals() {
  const grid = document.getElementById('eraGrid');
  grid.innerHTML = '';
  for (const era of ERAS) {
    const unlocked = progress.isUnlocked(era.id);
    const playable = unlocked && (era.fullyPlayable || chosenMode === MODE.CREATIVE);
    const m = era.manifest || {};
    const [skyA, skyB] = era.sky?.day || ['#456', '#234'];
    const card = document.createElement('div');
    card.className = 'era-card' + (unlocked ? '' : ' locked') + (playable ? '' : ' soon');
    // Paint each card with its own era's sky + ground so ages feel distinct.
    card.style.background =
      `linear-gradient(160deg, ${skyA}33, ${skyB}22), var(--panel)`;
    card.style.borderColor = `${era.ground}88`;
    const animals = (m.animals || []).slice(0, 3).join(' · ');
    card.innerHTML = `
      <div class="era-icon" style="filter: drop-shadow(0 2px 6px ${era.ground}aa)">${era.icon}</div>
      <h3>${m.title || era.name}</h3>
      <p class="era-sub">${m.subtitle || era.blurb}</p>
      ${animals ? `<p class="era-meta">🐾 ${animals}</p>` : ''}
      <div class="era-foot">${
        !unlocked ? '🔒 Locked'
          : playable ? '▶ Enter'
            : '🚧 Survival soon · Creative ok'
      }</div>
    `;
    if (playable) {
      card.onclick = () => { audio.play('ui'); startGame({ eraId: era.id, mode: chosenMode }); };
    }
    grid.appendChild(card);
  }
}

function syncSettingsUI() {
  const set = (id, val, checkbox = true) => {
    const e = document.getElementById(id);
    if (!e) return;
    if (checkbox) e.checked = !!val; else e.value = val;
  };
  set('lsSound', settings.get('sound'));
  set('lsMusic', settings.get('music'));
  set('lsReduceMotion', settings.get('reduceMotion'));
  set('lsZoom', settings.get('zoomPref') ?? 1, false);
}

function setMode(mode) {
  chosenMode = mode;
  document.getElementById('modeSurvival').classList.toggle('on', mode === MODE.SURVIVAL);
  document.getElementById('modeCreative').classList.toggle('on', mode === MODE.CREATIVE);
  document.getElementById('modeHint').textContent = mode === MODE.SURVIVAL
    ? '⚔️ Survival: gather, craft, survive, and earn Civ Points to open the next era.'
    : '🎨 Creative: free building with unlimited blocks, in any era you have unlocked.';
  const grid = document.getElementById('eraGrid');
  if (grid && grid.children.length) buildPortals();
}

function wire() {
  screens.landing = document.getElementById('landing');
  screens.portal = document.getElementById('portal');
  screens.howto = document.getElementById('howto');
  screens.settings = document.getElementById('settings');
  screens.game = document.getElementById('game');

  const click = (id, fn) => { const e = document.getElementById(id); if (e) e.onclick = () => { audio.resume(); audio.play('ui'); fn(); }; };

  // A shared reality link (?r=CODE) turns Play into a one-tap jump into that
  // exact world — the friend-sharing loop.
  const shared = parseRealityFromUrl();
  const playBtn = document.getElementById('playBtn');
  if (shared && playBtn) {
    const era = getEra(shared.era);
    const v = variantInfo(shared.era, shared.variant);
    playBtn.textContent = `▶ Play shared reality`;
    const sub = document.querySelector('.subtitle');
    if (sub) sub.textContent = `A friend shared a reality: ${era.icon} ${v ? v.name : era.name}. Press Play to enter their exact world.`;
    click('playBtn', () => startGame({ reality: shared }));
  } else {
    click('playBtn', () => { buildPortals(); show('portal'); });
  }
  click('continueBtn', () => {
    const save = SaveManager.load();
    if (save) startGame({ save });
  });
  click('howtoBtn', () => show('howto'));
  click('howtoBack', () => show('landing'));
  click('portalBack', () => show('landing'));
  click('settingsBtn', () => { syncSettingsUI(); show('settings'); });
  click('settingsBack', () => show('landing'));

  // Landing settings — apply immediately and persist, so players can mute
  // before any audio starts.
  const bind = (id, key, apply) => {
    const e = document.getElementById(id);
    if (!e) return;
    e.onchange = e.oninput = () => {
      const v = e.type === 'checkbox' ? e.checked : parseFloat(e.value);
      settings.set(key, v);
      apply?.(v);
    };
  };
  bind('lsSound', 'sound', (v) => audio.setSound(v));
  bind('lsMusic', 'music', (v) => audio.setMusic(v));
  bind('lsReduceMotion', 'reduceMotion', (v) => {
    try { document.body.classList.toggle('reduce-motion', v); } catch (e) { /* ignore */ }
  });
  bind('lsZoom', 'zoomPref');

  document.getElementById('modeSurvival').onclick = () => { audio.play('ui'); setMode(MODE.SURVIVAL); };
  document.getElementById('modeCreative').onclick = () => { audio.play('ui'); setMode(MODE.CREATIVE); };

  setMode(MODE.SURVIVAL);
  refreshLanding();
}

window.addEventListener('DOMContentLoaded', () => {
  loadSprites();
  wire();
  // Honor saved reduce-motion before any screen animates.
  if (settings.get('reduceMotion')) document.body.classList.add('reduce-motion');
  const sceneCanvas = document.getElementById('landingScene');
  if (sceneCanvas) landingScene = new LandingScene(sceneCanvas, { reduceMotion: settings.get('reduceMotion') });
  show('landing');
});
