class AudioSystem {
  constructor(){this.ctx=null;this.master=null;this.ambience=null;this.muted=false;this.started=false;this.musicTimer=null}
  async start(theme='cozy'){if(this.started)return;const AudioCtx=window.AudioContext||window.webkitAudioContext;if(!AudioCtx)return;this.ctx=new AudioCtx();await this.ctx.resume();this.master=this.ctx.createGain();this.master.gain.value=.28;this.master.connect(this.ctx.destination);this.started=true;this.startAmbience(theme)}
  setMuted(value){this.muted=value;if(this.master&&this.ctx)this.master.gain.setTargetAtTime(value?0:.28,this.ctx.currentTime,.03)}
  tone(freq,duration=.12,type='sine',gain=.12,slide=0){if(!this.started||this.muted)return;const now=this.ctx.currentTime,osc=this.ctx.createOscillator(),amp=this.ctx.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,now);if(slide)osc.frequency.exponentialRampToValueAtTime(Math.max(30,freq+slide),now+duration);amp.gain.setValueAtTime(.0001,now);amp.gain.exponentialRampToValueAtTime(gain,now+.01);amp.gain.exponentialRampToValueAtTime(.0001,now+duration);osc.connect(amp).connect(this.master);osc.start(now);osc.stop(now+duration+.02)}
  noise(duration=.12,gain=.08,cutoff=1600){if(!this.started||this.muted)return;const frames=Math.max(1,Math.floor(this.ctx.sampleRate*duration)),buffer=this.ctx.createBuffer(1,frames,this.ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<frames;i++)data[i]=(Math.random()*2-1)*(1-i/frames);const source=this.ctx.createBufferSource(),filter=this.ctx.createBiquadFilter(),amp=this.ctx.createGain();filter.type='lowpass';filter.frequency.value=cutoff;amp.gain.value=gain;source.buffer=buffer;source.connect(filter).connect(amp).connect(this.master);source.start()}
  jump(){this.tone(310,.14,'triangle',.11,190)} pounce(){this.noise(.1,.07,2200);this.tone(180,.15,'sawtooth',.055,250)} land(s=1){this.noise(.08,Math.min(.11,.045*s),700)}
  fish(){this.tone(740,.08,'sine',.09,180);setTimeout(()=>this.tone(980,.1,'sine',.07,210),55)} checkpoint(){[420,560,700].forEach((f,i)=>setTimeout(()=>this.tone(f,.15,'triangle',.08,80),i*75))} fail(){this.tone(220,.55,'sawtooth',.08,-130)} win(){[392,523,659,784].forEach((f,i)=>setTimeout(()=>this.tone(f,.3,'triangle',.09,50),i*90))} tick(u=false){this.tone(u?920:640,.045,'square',u?.07:.035)} meow(){this.tone(520,.18,'sawtooth',.04,-150)}
  startAmbience(theme){if(!this.started)return;if(this.musicTimer)clearInterval(this.musicTimer);const scale=theme==='neon'?[220,261.6,329.6,392]:theme==='penthouse'?[196,246.9,293.7,370]:[174.6,220,261.6,329.6];let step=0;this.musicTimer=setInterval(()=>{if(this.muted||!this.started)return;const f=scale[step++%scale.length];this.tone(f,.55,'sine',.018,4);if(step%2===0)this.tone(f*2,.22,'triangle',.008)},theme==='neon'?330:520)}
  stop(){if(this.musicTimer)clearInterval(this.musicTimer);this.musicTimer=null}
}